services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: paylane
      POSTGRES_PASSWORD: paylane_dev_pw
      POSTGRES_DB: paylane
    volumes:
      - paylane-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paylane -d paylane"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  mandate-svc:
    image: ghcr.io/rohitkumar7299/paylane-mandate-svc:latest
    environment:
      DATABASE_URL: postgresql://paylane:paylane_dev_pw@postgres:5432/paylane
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"

  payment-svc:
    image: ghcr.io/rohitkumar7299/paylane-payment-svc:latest
    environment:
      DATABASE_URL: postgresql://paylane:paylane_dev_pw@postgres:5432/paylane
      REDIS_URL: redis://redis:6379/0
      MANDATE_SVC_URL: http://mandate-svc:3001
    depends_on:
      mandate-svc:
        condition: service_started
    ports:
      - "3002:3002"

  ledger-svc:
    image: ghcr.io/rohitkumar7299/paylane-ledger-svc:latest
    environment:
      DATABASE_URL: postgresql://paylane:paylane_dev_pw@postgres:5432/paylane
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3003:3003"

  settlement-worker:
    image: ghcr.io/rohitkumar7299/paylane-settlement-worker:latest
    environment:
      DATABASE_URL: postgresql://paylane:paylane_dev_pw@postgres:5432/paylane
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  portal:
    image: ghcr.io/rohitkumar7299/paylane-portal:latest
    environment:
      PAYMENT_SVC_URL: http://payment-svc:3002
      MANDATE_SVC_URL: http://mandate-svc:3001
      LEDGER_SVC_URL: http://ledger-svc:3003
    depends_on:
      payment-svc:
        condition: service_started
      mandate-svc:
        condition: service_started
      ledger-svc:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  paylane-pgdata:
